### ISSUE TITLE
Installing with pip fails

### ISSUE THREAD

**Issue by sfrimann** [jwg4/exact_cover#45]
Installing with pip fails with this error

I'm not very experienced with builds so I'm not completely sure what the issue is. Hope someone can provide some insights
```
pip install exact-cover
Collecting exact-cover
  Using cached exact_cover-0.8.0.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy<2.0,>=1.20 in ./opt/miniconda3/lib/python3.9/site-packages (from exact-cover) (1.20.3)
Collecting setuptools<52.0.0,>=51.1.2
  Using cached setuptools-51.3.3-py3-none-any.whl (786 kB)
Building wheels for collected packages: exact-cover
  Building wheel for exact-cover (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for exact-cover (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      A setup.py file already exists. Using it.
      running build
      running build_py
      creating /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build
      creating /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/lib.macosx-10.9-x86_64-cpython-39
      creating /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/lib.macosx-10.9-x86_64-cpython-39/exact_cover
      copying exact_cover/error.py -> /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/lib.macosx-10.9-x86_64-cpython-39/exact_cover
      copying exact_cover/io.py -> /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/lib.macosx-10.9-x86_64-cpython-39/exact_cover
      copying exact_cover/__init__.py -> /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/lib.macosx-10.9-x86_64-cpython-39/exact_cover
      copying exact_cover/helpers.py -> /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/lib.macosx-10.9-x86_64-cpython-39/exact_cover
      running build_ext
      building 'exact_cover_impl' extension
      creating /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39
      creating /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src
      x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -D_FORTIFY_SOURCE=2 -isystem /Users/sfrimann/opt/miniconda3/include -Isrc/ -I/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/sfrimann/opt/miniconda3/include/python3.9 -c src/dlx.c -o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/dlx.o
      x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -D_FORTIFY_SOURCE=2 -isystem /Users/sfrimann/opt/miniconda3/include -Isrc/ -I/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/sfrimann/opt/miniconda3/include/python3.9 -c src/exact_cover.c -o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/exact_cover.o
      x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -D_FORTIFY_SOURCE=2 -isystem /Users/sfrimann/opt/miniconda3/include -Isrc/ -I/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/sfrimann/opt/miniconda3/include/python3.9 -c src/quad_linked_list.c -o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/quad_linked_list.o
      x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -arch x86_64 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -D_FORTIFY_SOURCE=2 -isystem /Users/sfrimann/opt/miniconda3/include -Isrc/ -I/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/sfrimann/opt/miniconda3/include/python3.9 -c src/sparse_matrix.c -o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/sparse_matrix.o
      x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/sfrimann/opt/miniconda3/lib -L/Users/sfrimann/opt/miniconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/sfrimann/opt/miniconda3/lib -L/Users/sfrimann/opt/miniconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/sfrimann/opt/miniconda3/lib -L/Users/sfrimann/opt/miniconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sfrimann/opt/miniconda3/include -D_FORTIFY_SOURCE=2 -isystem /Users/sfrimann/opt/miniconda3/include /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/dlx.o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/exact_cover.o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/quad_linked_list.o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/temp.macosx-10.9-x86_64-cpython-39/src/sparse_matrix.o -o /private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build/lib.macosx-10.9-x86_64-cpython-39/exact_cover_impl.cpython-39-darwin.so
      ld: warning: -pie being ignored. It is only used when linking a main executable
      ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
      clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/Users/sfrimann/opt/miniconda3/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
      Traceback (most recent call last):
        File "/Users/sfrimann/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/sfrimann/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/sfrimann/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
          return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
        File "/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 78, in make_in
          wb.build()
        File "/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 110, in build
          self._build(zip_file)
        File "/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 162, in _build
          self._run_build_command(setup)
        File "/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-build-env-d6x0vl9y/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 190, in _run_build_command
          subprocess.check_call(
        File "/Users/sfrimann/opt/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/sfrimann/opt/miniconda3/bin/python3.9', '/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/setup.py', 'build', '-b', '/private/var/folders/yd/4692dj8s6k549wb83k49zg0w0000gn/T/pip-install-sb538he2/exact-cover_f7d0d46c5a24443d9e8b5660f13a77c0/build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for exact-cover
Failed to build exact-cover
ERROR: Could not build wheels for exact-cover, which is required to install pyproject.toml-based projects
```

**Comment by sfrimann** [comment]
Turns out the issue was that command line tools were installed twice. Sorry for the spam

**Comment by jwg4** [comment]
thanks anyway for reporting!
