### ISSUE TITLE
get_all_solutions crash

### ISSUE THREAD

**Issue by parmentelat** [jwg4/exact_cover#84]
hi, just ran into this crash

I can provide more details on the input - hopefully I can get this library of problems to solve in the near future
but in the meanwhile maybe this is enough for you to spot the problem ?

```
Traceback (most recent call last):
  File "~/git/exact-cover-py/benchmark/benchmark.py", line 130, in <module>
    main()
  File "~/git/exact-cover-py/benchmark/benchmark.py", line 127, in main
    run_once(run_index, args.full)
  File "~/git/exact-cover-py/benchmark/benchmark.py", line 112, in run_once
    [run_exact_cover(name, problem, run_index, size) for size in sizes])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/git/exact-cover-py/benchmark/benchmark.py", line 47, in run_exact_cover
    solutions = [get_exact_covers(problem["data"], max_count=max_count)]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/exact-cover-py/lib/python3.12/site-packages/exact_cover/wrapper.py", line 62, in get_all_solutions
    return _solutions_array_to_set(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/exact-cover-py/lib/python3.12/site-packages/exact_cover/wrapper.py", line 45, in _solutions_array_to_set
    return set([tuple(truncate(row)) for row in a])
                      ^^^^^^^^^^^^^
  File "~/miniconda3/envs/exact-cover-py/lib/python3.12/site-packages/exact_cover/wrapper.py", line 41, in truncate
    return truncate(row[:-1])
           ^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/exact-cover-py/lib/python3.12/site-packages/exact_cover/wrapper.py", line 41, in truncate
    return truncate(row[:-1])
           ^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/exact-cover-py/lib/python3.12/site-packages/exact_cover/wrapper.py", line 41, in truncate
    return truncate(row[:-1])
           ^^^^^^^^^^^^^^^^^^
  [Previous line repeated 990 more times]
  File "~/miniconda3/envs/exact-cover-py/lib/python3.12/site-packages/exact_cover/wrapper.py", line 37, in truncate
    if all(x == 0 for x in row):
          ^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

**Comment by jwg4** [comment]
fixed by #85
